.TH lightdm-gtk-greeter-settings 8 "June 26, 2015"

.SH NAME
lightdm-gtk-greeter-settings - Settings editor for LightDM GTK+ Greeter

.SH SYNOPSIS
\fBlightdm\-gtk\-greeter\-settings\fR [\fIOPTIONS\fR]

.SH DESCRIPTION
\fBlightdm\-gtk\-greeter\-settings\fR is a settings editor for LightDM's GTK+ Greeter.

.PP
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-s\fR SOCKET_ID, \fB\-\-socket\-id\fR SOCKET_ID
sets the settings manager socket
.TP
\fB\-\-use\-gtk\-header\fR
use Gtk header bars for the main window's display
.TP
\fB\-\-test\-socket\fR
enables testing for embedded mode
.PP

.SH "SEE ALSO"
.BR lightdm (1)

.SH AUTHOR
\fBlightdm-gtk-greeter-settings\fR was written by Andrew P. <pan.pav.7c5@gmail.com>.
.PP
This manual page was written by James Lu <glolol1@hotmail.com>
for the Debian project (but may be used by others).
